config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	get 'versions', to: 'posts#versions'
  	get 'restore_version', to: 'posts#restore_version'
  	get 'compare_versions', to: 'posts#compare_versions'
  end

  root 'posts#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_paper_trail
  before_save :strip_html_symbols

  def strip_html_symbols
    self.content = ActionView::Base.full_sanitizer.sanitize(self.content).html_safe
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def versions
    post = Post.find(params[:post_id])
    @versions = post.versions
  end

  def restore_version
    @post = Post.find(params[:post_id])
    @post.update_column(:title, params[:title])
    @post.update_column(:content, params[:content])
    respond_to do |format|
      format.html { redirect_to @post, notice: "Book was successfully updated." }
      format.json { render :show, status: :ok, location: @post }
    end
  end

  def compare_versions
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= tinymce_assets %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <span class="success_msgs"> 
      <% if notice %>
        <p class="alert alert-success"> <%= notice %> </p> 
      <% end %> 
    </span>

    <span class="error_msgs"> 
      <% if alert %>
        <p class="alert alert-success"><%= alert %></p> 
      <% end %> 
    </span>
    <header class="navbar navbar-default" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <div id="logo" class="navbar-brand"><%= link_to "Create Book", root_path %></div>
          <div id="logo" class="navbar-brand"><%= link_to "All Books Detail", posts_path %> </div>
        </div>
      </div>
    </header>
    <div id="main_content" class="container">
      <%= yield %>
    </div>
  </div>
</div>
<script>
    setTimeout("$('.error_msgs').fadeOut('slow')", 5000)
    setTimeout("$('.success_msgs').fadeOut('slow')", 5000)
</script>
</body>
</html>

app/views/posts/_form.html.erb
<%= tinymce %>
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, :class => "tinymce", :rows => 20, :cols => 60 %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="panel-body panel-height">
  <table class="table table-bordered">
   <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th colspan="4">Actions</th>
    </tr>
   </thead>
   <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'All Version', post_versions_path(post) %></td>
      </tr>
    <% end %>  
   </tbody>
  </table>
    <br></br>
</div>

app/views/posts/new.html.erb
<%= tinymce_assets %>
<div class="header" style="text-align: center"%>
  <h1>Create Book</h1>
</div>
<div class="form" style="text-align: center"%>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="panel-body panel-height">
  <table class="table table-bordered">
   <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
    </tr>
   </thead>
   <tbody>
       <td> <%= @post.title %></td>
       <td> <%= @post.content %></td>
   </tbody>
  </table>
    <br></br>
</div>

app/views/posts/versions.html.erb
<div class="panel-body panel-height">
  <table class="table table-bordered">
   <thead>
    <tr>
      <th scope="col">Created At</th>
      <th scope="col">Title Versions</th>
      <th scope="col">Content Versions</th>
      <th scope="col">Restore Version</th>
      <th scope="col">Compare Version</th>
    </tr>
   </thead>
   <tbody>
    <% @versions.reverse.each do |version| %>
      <% if version.changeset[:title].present? %>
        <% title = Post.find_by(id: version.item_id).title %>
        <% content = Post.find_by(id: version.item_id).content %>
        <tr class="<%= (version.changeset[:title].last == title && version.changeset[:content].last == content) ? 'red' : 'black' %>">
      <% end %>
        <td><%= version.created_at %></td>
        <% if version.changeset[:title].present?  %>
          <td><%= version.changeset[:title].last %></td>
        <% else %>
          <td><%= Post.find_by(id: version.item_id).title %>
        <% end %>
        <td><%= version.changeset[:content].last %></td>
        <% if version.changeset[:title].present? %>
          <td><%= link_to "Restore", post_restore_version_path(title: version.changeset[:title].last, content: version.changeset[:content].last, post_id: version.item_id) %>
        <% else %>
          <td><%= link_to "Restore", post_restore_version_path(title: Post.find_by(id: version.item_id).title, content: version.changeset[:content].last, post_id: version.item_id) %>
        <% end %>
        <td><%= check_box_tag 'compare[]', version.id ,false, class: "name" %> 
      </tr>
    <% end %>  
   </tbody>
  </table>
  <div class="form" style="text-align: center"%>
    <%= button_to "Compare", onclick: "CompareVersions();",class: "btn btn-default btn-primary" , action: "compare_versions" %>
  </div>

    <br></br>
</div>